serial_dump:	serial_dump.cc
	g++ -Wall -Wno-misleading-indentation -I../src -O2 -o serial_dump serial_dump.cc ../src/format.cpp

read_log:	read_log.cc
	g++ -Wall -Wno-misleading-indentation -I../src -O2 -o read_log read_log.cc ../src/format.cpp

clean:
	rm serial_dump read_log

